# syntax=docker/dockerfile:1

FROM openjdk:17
ADD target/onlineLearning-0.0.1-SNAPSHOT.jar onlineLearning-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "onlineLearning-0.0.1.SNAPSHOT.jar"]
EXPOSE 8080