version: '3.3'
services:
  mysql:
    image: mysql:8.1.0
#    volumes:
#      - mysql-volume: /var/lib/mysql
    networks:
      springdemo-net:
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: swponlinelearning
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 20s
      timeout: 10s
      retries: 3
  app:
    image: quangthang2212/demo-spring-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      springdemo-net:
    environment:
      MYSQL_HOST: mysql
networks:
  springdemo-net:
volumes:
  mysql-volume: